### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "testpassword"
}


### Login
POST http://localhost:3000/auth/login